// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarWars.Models;

#nullable disable

namespace New_Harbinger.Migrations
{
    [DbContext(typeof(HarbingerDbContext))]
    partial class HarbingerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("StarWars.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Affiliation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CharacterId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterId = 1,
                            Affiliation = "Jedi",
                            Name = "Rey Skywalker",
                            Species = "Human"
                        },
                        new
                        {
                            CharacterId = 2,
                            Affiliation = "Scoundrel",
                            Name = "Fin",
                            Species = "Human"
                        },
                        new
                        {
                            CharacterId = 3,
                            Affiliation = "Rebel",
                            Name = "Po Dameron",
                            Species = "Human"
                        },
                        new
                        {
                            CharacterId = 4,
                            Affiliation = "Exile",
                            Name = "Metra Surik",
                            Species = "Human"
                        },
                        new
                        {
                            CharacterId = 5,
                            Affiliation = "Scout",
                            Name = "Zaalbarr",
                            Species = "Wookie"
                        },
                        new
                        {
                            CharacterId = 6,
                            Affiliation = "Bounty Hunter",
                            Name = "Greedo",
                            Species = "Rodian"
                        },
                        new
                        {
                            CharacterId = 7,
                            Affiliation = "Assassin",
                            Name = "Hk-47",
                            Species = "Droid"
                        },
                        new
                        {
                            CharacterId = 8,
                            Affiliation = "Mandalorian",
                            Name = "Bralor Starkiller",
                            Species = "Human"
                        },
                        new
                        {
                            CharacterId = 9,
                            Affiliation = "Jedi",
                            Name = "Ahsoka Tano",
                            Species = "Twilek"
                        },
                        new
                        {
                            CharacterId = 10,
                            Affiliation = "Mandalorian",
                            Name = "Din Djarin",
                            Species = "Human"
                        },
                        new
                        {
                            CharacterId = 11,
                            Affiliation = "Sith Lord",
                            Name = "Sheev Palpatine",
                            Species = "Human"
                        },
                        new
                        {
                            CharacterId = 12,
                            Affiliation = "Sith Lord",
                            Name = "Darth Malak",
                            Species = "Human"
                        },
                        new
                        {
                            CharacterId = 13,
                            Affiliation = "Jedi",
                            Name = "Cal Kestis",
                            Species = "Human"
                        },
                        new
                        {
                            CharacterId = 14,
                            Affiliation = "Jedi",
                            Name = "Master Vrook",
                            Species = "Human"
                        },
                        new
                        {
                            CharacterId = 15,
                            Affiliation = "Marauder",
                            Name = "Sleemo Lacerus",
                            Species = "Zabraak"
                        },
                        new
                        {
                            CharacterId = 16,
                            Affiliation = "Jedi Historian",
                            Name = "Atris",
                            Species = "Human"
                        },
                        new
                        {
                            CharacterId = 17,
                            Affiliation = "Jedi",
                            Name = "Quade Lancaster",
                            Species = "Human"
                        },
                        new
                        {
                            CharacterId = 18,
                            Affiliation = "Clone",
                            Name = "Boba Fett",
                            Species = "Human"
                        },
                        new
                        {
                            CharacterId = 19,
                            Affiliation = "General",
                            Name = "Carth Onasi",
                            Species = "Human"
                        },
                        new
                        {
                            CharacterId = 20,
                            Affiliation = "Scoundrel",
                            Name = "Mission Vao",
                            Species = "Twilek"
                        },
                        new
                        {
                            CharacterId = 21,
                            Affiliation = "Mandalorian",
                            Name = "Canderous Ordo",
                            Species = "Human"
                        },
                        new
                        {
                            CharacterId = 22,
                            Affiliation = "Mandalorian",
                            Name = "Bo-Katan Kryze",
                            Species = "Human"
                        },
                        new
                        {
                            CharacterId = 23,
                            Affiliation = "Pilot",
                            Name = "Jek Porkins",
                            Species = "Human"
                        },
                        new
                        {
                            CharacterId = 24,
                            Affiliation = "Sith Admiral",
                            Name = "Piett",
                            Species = "Human"
                        },
                        new
                        {
                            CharacterId = 25,
                            Affiliation = "Inquistor",
                            Name = "Trilla",
                            Species = "Human"
                        });
                });

            modelBuilder.Entity("StarWars.Models.Quest", b =>
                {
                    b.Property<int>("QuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("QuestId");

                    b.HasIndex("CharacterId");

                    b.ToTable("Quests");

                    b.HasData(
                        new
                        {
                            QuestId = 1,
                            CharacterId = 1,
                            Description = "Quest begins where Rey has a premonition",
                            Title = "Jaku",
                            Type = "Main Quest"
                        },
                        new
                        {
                            QuestId = 2,
                            CharacterId = 0,
                            Description = "Char Meets Master Atris",
                            Title = "Academy on Telos",
                            Type = "Main Quest"
                        },
                        new
                        {
                            QuestId = 3,
                            CharacterId = 0,
                            Description = "Char travels to Jedha in search of holocron",
                            Title = "Memories Unlimited",
                            Type = "Main Quest"
                        },
                        new
                        {
                            QuestId = 4,
                            CharacterId = 0,
                            Description = "Char comes face to face with an inquisitor",
                            Title = "Trouble on Tanalor",
                            Type = "Main Quest"
                        },
                        new
                        {
                            QuestId = 5,
                            CharacterId = 0,
                            Description = "Rey meets char outside shuttle for news",
                            Title = "Back to Jaku",
                            Type = "Main Quest"
                        },
                        new
                        {
                            QuestId = 6,
                            CharacterId = 0,
                            Description = "Char begins reliving inquistor standoff",
                            Title = "A disturbance in the force",
                            Type = "Main Quest"
                        },
                        new
                        {
                            QuestId = 7,
                            CharacterId = 0,
                            Description = "The spirit of palpatine endures",
                            Title = "Palpatine Returns",
                            Type = "Main Quest"
                        },
                        new
                        {
                            QuestId = 8,
                            CharacterId = 0,
                            Description = "beyond the astroid belt a star destroyer is found",
                            Title = "Rebel Forces Engage Defectors",
                            Type = "Main Quest"
                        },
                        new
                        {
                            QuestId = 9,
                            CharacterId = 0,
                            Description = "Po meets Meetra Surik a Jedi exile living among mandalorians",
                            Title = "Po Dameron crash lands on Dxun",
                            Type = "Main Quest"
                        },
                        new
                        {
                            QuestId = 10,
                            CharacterId = 0,
                            Description = "surviving imperials flee to planet beneath burning star destroyer",
                            Title = "Jek Porkins pulls forces back",
                            Type = "Main Quest"
                        },
                        new
                        {
                            QuestId = 11,
                            CharacterId = 0,
                            Description = "An unexpected answer from a new threat",
                            Title = "Piett calls for reinforcements",
                            Type = "Main Quest"
                        },
                        new
                        {
                            QuestId = 12,
                            CharacterId = 0,
                            Description = "Darth Malak emerges from the outer rim with inquisitors",
                            Title = "The Leviathan",
                            Type = "Main Quest"
                        },
                        new
                        {
                            QuestId = 13,
                            CharacterId = 0,
                            Description = "Po and Meetra search for imperial crash landers",
                            Title = "Dxun Jungle",
                            Type = "Main Quest"
                        },
                        new
                        {
                            QuestId = 14,
                            CharacterId = 0,
                            Description = "Atris continues Quades jedi training",
                            Title = "Back to Telos",
                            Type = "Side Quest"
                        },
                        new
                        {
                            QuestId = 15,
                            CharacterId = 0,
                            Description = "Rey begins searching for the new sith threat",
                            Title = "An Old Order",
                            Type = "Main Quest"
                        });
                });

            modelBuilder.Entity("StarWars.Models.Quest", b =>
                {
                    b.HasOne("StarWars.Models.Character", "Character")
                        .WithMany("Quests")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("StarWars.Models.Character", b =>
                {
                    b.Navigation("Quests");
                });
#pragma warning restore 612, 618
        }
    }
}
